### PR TITLE
implement field_reservation table

### PR DESCRIPTION
**Pull request by johndonor3**
This PR implements a field reservation table to allow multiple people to work on new fields/designs at the same time without stepping on toes. This solves COS-55. 

@blanton144 and @imedan will be glad this is finally done; sorry it got pushed after the holiday!

### CODE REVIEW

**Review by albireox — APPROVED** [review]
This looks good to me. I guess another solution would be to do this directly in the `field` table and then `requestNext` would create empty field entries that would be filled out later when the fields are actually being loaded. But I'm not especially attached to that idea.

I don't know if in addition to that you want to add some form of constraint to enforce it, for example requiring that `field.field_id` must be lower than the max value of `field_reservation.field_id`. But since this is ultimately an internal tool it's probably not necessary.

**Comment by johndonor3** [comment]
After a bit of googling, constraints referencing other tables are basically impossible unless it's a foreign key. This seems reasonable really. So I think the options are 1) enforce targetdb.field.field_id has a FK referencing targetdb.field_reservation.field_id, or 2) honor system. Since we're talking about 2 people at the moment (and probably < 5 for the life of the survey, if that), and that seems like a slightly odd FK, I'm leaning towards honor system. But it's also not a totally unreasonable FK? I'm going to sleep on it and be open to advice for a day or two. Also we can definitely add that FK constraint at any time in the future. @blanton144 @imedan

**Comment by albireox** [comment]
The honour system sounds reasonable enough for this purpose.

**Comment by imedan** [comment]
@johndonor3  to double check how the function you implemented within this table works, is it correct in saying that this function reserves the N field_ids from the maximum in field_id in targetdb.field? If so, I don't know if that is exactly what me and @blanton144 want (possibly). Mainly, I think it would be good to differentiate between commissioning/science fields here. This is because commissioning fields will take 16000 <= field_id < 100000 and science will take field_id >= 100000. So, when have both commissioning and science fields in targetdb.field (which will be true between APO operations/LCO commissioning), it seems this function won't exactly work as intended? It might make sense to specify if the user is requesting to reserve fields in either the commissioning or science range then when finding this maximum then?

Additionally, does it not make sense for field_id to have a unique constraint in this new table (so it cannot be reserved again)?

**Comment by johndonor3** [comment]
@imedan Yeah the unique constraint definitely makes sense.

I thought about the change from commissioning to science. If we simply add N - 1 (so 999,999) to the res table then the starting field_id would be 1,000,000. This allows the code to be clean, and we'd need some kind of intervention before starting science anyway.

Or are you concerned y'all would be requesting science and commissioning ranges at the same time? If you're fairly confident that will happen, I can hard code a switch at 1e6. But it hurts my soul a little to hardcode something like that. If you aren't particularly convinced, this is something that can easily be added to sdssdb later, with no further changes to the database itself.

**Comment by johndonor3** [comment]
Oh, duh. I'm using field_id as a primary key in the res table, so it's already unique :)

**Comment by imedan** [comment]
@johndonor3 Ok, good to hear it is unique then (I see now too that it makes sense it is).

For clarification, I think we are starting science at 100,000 (not 1,000,000). Also, I think we may reserve science/commissioning at the same time? Or its possibly at least. This is something I would really want to check with @blanton144 to see how he feels about it one way or another.

**Pull request merged**
